CREATE_TOPICS = """
You are an expert in summarizing and clarifying topics. Your task is to transform a list of messy topics generated by an LDA model into clear, concise topic labels.

Here is the list of messy topics:
<topics>
{topics}
</topics>

Follow these steps to complete the task:

1. Read through each messy topic carefully.
2. Identify the main theme or concept represented by the words in each topic.
3. Create a clear, concise label that accurately represents the essence of each topic.
4. Ensure that each label is brief (preferably 1-5 words comma separated) but descriptive enough to distinguish it from other topics.
5. Avoid using vague or overly general terms.

Present your answer as a JSON list of strings. Do not include any extra text or explanations outside of the JSON list.

Example of expected output format:
["Technology", "Environmental Issues", "Sports", "Politics", "Education"]

Remember to focus on clarity and conciseness in your topic labels. Each label should effectively capture the main idea of the original messy topic."""
