CREATE_TOPICS = """
You are an expert in summarizing and clarifying topics. Your task is to transform a list of messy topics generated by an LDA model into clear, concise topic labels.

Here is the list of messy topics:
<topics>
{topics}
</topics>

Follow these steps to complete the task:

1. Read through each messy topic carefully.
2. Identify the main theme or concept represented by the words in each topic.
3. Create a clear, concise label that accurately represents the essence of each topic.
4. Ensure that each label is brief (preferably 1-5 words comma separated) but descriptive enough to distinguish it from other topics.
5. Avoid using vague or overly general terms.

Present your answer as a JSON list of strings. Do not include any extra text or explanations outside of the JSON list.

Example of expected output format:
["Technology", "Environmental Issues", "Sports", "Politics", "Education"]

Remember to focus on clarity and conciseness in your topic labels. Each label should effectively capture the main idea of the original messy topic."""

EXAMPLE1 = """
{
  "content_type": "paragraph",
  "is_sufficient": true,
  "topics": ["Topic 1", "Topic 2"]
}
"""

EXAMPLE2 = """
{
  "content_type": "footer",
  "is_sufficient": false,
  "topics": []
}
"""

CLASSIFY_PROMPT = """
You are an expert content classifier. Your task is to analyze a given text excerpt and perform the following:

1. **Determine the type of the content.**
2. **Assess if the content is sufficient for topic classification.**
3. **If sufficient, select up to 3 topics from the provided list that best describe the content.**
4. **Only the topic id is required in the output**

Here is the text excerpt you need to analyze:
```
<text>
{text}
</text>
```

Here are the candidate topics to choose from:
```
<topics>
{topics}
</topics>
```

### Task Requirements:
1. **Determine the content type** from the following list:
  * `paragraph`: A continuous block of prose.
  * `table`: Text formatted with rows/columns (e.g., "Product | Price").
  * `list`: Items separated by numbers, bullets, or dashes (e.g., "- Item 1").
  * `header/footer/index`: Titles/footers/navigation markers.
  * `figure_caption`: Descriptions of images/diagrams.
  * `citation`: section with reference or citation of author, book.
  * `other`: None of the above.

2. **Assess sufficiency**: **Strict** evaluation if the text excerpt contains sufficient information to reliably determine its main themes or subject matter. 
- Set `"is_sufficient"` to:
     * `true` only if the text contains enough distinct information to confidently identify its core themes.
     * `false` for vague, incomplete, or ambiguous content (e.g., "See Section 4" or isolated keywords).

3. **Select Topics** (only if sufficient):
   - Choose **up to three most relevant topics** from the provided list. 
   - Prioritize specificity: e.g., prefer "Climate Change Causes" over "Environment".
   - Do NOT include topics that are:
     * Too broad/unrelated
     * Duplicates of other selected items
     * Not explicitly listed in `<topics>`

### Output Format:
Output your answer as a JSON object with the following keys:
- `"content_type"`: A string indicating the type of content (from the list above).
- `"is_sufficient"`: A boolean indicating if the content is sufficient for topic classification.
- `"topics"`: A JSON array of strings containing the selected topics (empty if `"is_sufficient"` is `false`).

#### Example Outputs:
```json
{example1}
```
```json
{example2}
```

### Reminders:
- Select no more than 3 topics.
- Use only topics from the provided list.
- Ensure the selected topics are the most relevant to the text content if `"is_sufficient"` is `true`.
- For ambiguous headers like "Chapter 3: Results", classify as `header` and mark insufficient.

**Final Warning:** Strictly adhere to JSON syntax. Do not include any extra text or explanations outside of the JSON object.
""".strip()
