name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install black flake8
      - name: Run Black (Check Formatting)
        run: black . --check
      - name: Run Flake8 (Linting)
        run: flake8 --ignore=E501
